apiVersion: v1
kind: Service
metadata:
  name: bhs-api-svc
  namespace: bhs
  labels:
    app: bhs-api
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: bhs-api
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
