#!/bin/sh
set -e

# Inject environment variables into the built JavaScript
# This allows runtime configuration without rebuilding the container

CONFIG_FILE="/usr/share/nginx/html/config.js"

cat > "$CONFIG_FILE" << ENVCONFIG
// Runtime configuration injected at container startup
window.__RUNTIME_CONFIG__ = {
  // API Configuration
  VITE_API_BASE_URL: "${VITE_API_BASE_URL:-}",

  // Azure AD / Entra ID Authentication
  VITE_AZURE_CLIENT_ID: "${VITE_AZURE_CLIENT_ID:-}",
  VITE_AZURE_TENANT_ID: "${VITE_AZURE_TENANT_ID:-}",
  VITE_AZURE_AUTHORITY: "${VITE_AZURE_AUTHORITY:-}",
  VITE_AZURE_REDIRECT_URI: "${VITE_AZURE_REDIRECT_URI:-}",
  VITE_AZURE_POST_LOGOUT_REDIRECT_URI: "${VITE_AZURE_POST_LOGOUT_REDIRECT_URI:-}",
  VITE_AZURE_ADMIN_GROUP_ID: "${VITE_AZURE_ADMIN_GROUP_ID:-}",
  VITE_AZURE_CONTROL_PANEL_GROUP_ID: "${VITE_AZURE_CONTROL_PANEL_GROUP_ID:-}",
  VITE_ENABLE_ENTRA_AUTH: "${VITE_ENABLE_ENTRA_AUTH:-true}",

  // Azure Blob Storage
  VITE_STORAGE_CONTAINER_NAME: "${VITE_STORAGE_CONTAINER_NAME:-audio-uploads}",

  // Azure OpenAI Realtime API
  VITE_AZURE_OPENAI_REALTIME_API_VERSION: "${VITE_AZURE_OPENAI_REALTIME_API_VERSION:-2025-04-01-preview}",
  VITE_AZURE_OPENAI_REALTIME_DEPLOYMENT: "${VITE_AZURE_OPENAI_REALTIME_DEPLOYMENT:-gpt-realtime}",
  VITE_AZURE_OPENAI_REALTIME_KEY: "${VITE_AZURE_OPENAI_REALTIME_KEY:-}",
  VITE_AZURE_OPENAI_RESOURCE_NAME: "${VITE_AZURE_OPENAI_RESOURCE_NAME:-}",
  VITE_AZURE_OPENAI_WEBRTC_REGION: "${VITE_AZURE_OPENAI_WEBRTC_REGION:-eastus2}",

  // Agent Voice Configuration
  VITE_TARS_VOICE: "${VITE_TARS_VOICE:-echo}",
  VITE_JEKYLL_VOICE: "${VITE_JEKYLL_VOICE:-shimmer}",
  VITE_JEKYLL_PHQ2_THRESHOLD: "${VITE_JEKYLL_PHQ2_THRESHOLD:-1}",
  VITE_MATRON_VOICE: "${VITE_MATRON_VOICE:-coral}",

  // Feature Flags (Production defaults)
  VITE_DEV_ENVIRONMENT: "${VITE_DEV_ENVIRONMENT:-false}",
  VITE_DEV_ENVIRONMENT_TEXT: "${VITE_DEV_ENVIRONMENT_TEXT:-}",
  VITE_AUTO_START_SESSION: "${VITE_AUTO_START_SESSION:-true}",
  VITE_ENABLE_DEBUG_LOGGING: "${VITE_ENABLE_DEBUG_LOGGING:-false}",
  VITE_ENABLE_FFMPEG_WORKER: "${VITE_ENABLE_FFMPEG_WORKER:-true}",
  VITE_ENABLE_KINTSUGI: "${VITE_ENABLE_KINTSUGI:-true}",
  VITE_ENABLE_TRANSCRIPTION: "${VITE_ENABLE_TRANSCRIPTION:-true}",
  VITE_ENABLE_VERBOSE_LOGGING: "${VITE_ENABLE_VERBOSE_LOGGING:-false}",
  VITE_ENABLE_AI_RISK_ASSESSMENT: "${VITE_ENABLE_AI_RISK_ASSESSMENT:-true}",
  VITE_AGENT_MODE_ENABLED: "${VITE_AGENT_MODE_ENABLED:-false}",
  VITE_ENABLE_JEKYLL_AGENT: "${VITE_ENABLE_JEKYLL_AGENT:-true}",

  // Voice Recording Configuration
  VITE_ENABLE_SESSION_VOICE_RECORDING: "${VITE_ENABLE_SESSION_VOICE_RECORDING:-true}",

  // Biometric Data Service Configuration
  VITE_BIOMETRIC_SAVE_DELAY_MS: "${VITE_BIOMETRIC_SAVE_DELAY_MS:-2000}",
  VITE_MATRON_MAX_COLLECTION_ATTEMPTS: "${VITE_MATRON_MAX_COLLECTION_ATTEMPTS:-2}",
  VITE_AGENT_HANDOFF_DELAY_MS: "${VITE_AGENT_HANDOFF_DELAY_MS:-2000}",

  // API Request Configuration
  VITE_API_TIMEOUT_MS: "${VITE_API_TIMEOUT_MS:-30000}",
  VITE_API_MAX_RETRIES: "${VITE_API_MAX_RETRIES:-3}",
  VITE_API_RETRY_DELAY_MS: "${VITE_API_RETRY_DELAY_MS:-1000}",

  // WebRTC Configuration
  VITE_REALTIME_MAX_RECONNECTION_ATTEMPTS: "${VITE_REALTIME_MAX_RECONNECTION_ATTEMPTS:-3}",
  VITE_REALTIME_RECONNECTION_DELAY_MS: "${VITE_REALTIME_RECONNECTION_DELAY_MS:-2000}",
  VITE_REALTIME_DATA_CHANNEL_TIMEOUT_MS: "${VITE_REALTIME_DATA_CHANNEL_TIMEOUT_MS:-5000}",
  VITE_INITIAL_GREETING_SESSION_DELAY_MS: "${VITE_INITIAL_GREETING_SESSION_DELAY_MS:-1500}",
  VITE_INITIAL_GREETING_RESPONSE_DELAY_MS: "${VITE_INITIAL_GREETING_RESPONSE_DELAY_MS:-300}",

  // Polling Configuration
  VITE_CONTROL_PANEL_REFRESH_INTERVAL: "${VITE_CONTROL_PANEL_REFRESH_INTERVAL:-30}",
  VITE_JOB_POLL_INTERVAL_MS: "${VITE_JOB_POLL_INTERVAL_MS:-10000}",
  VITE_POLL_INTERVAL_MS: "${VITE_POLL_INTERVAL_MS:-1000}"
};
ENVCONFIG

echo "Runtime configuration injected into $CONFIG_FILE"
